version: '3'
services:
  app:
    restart: always
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./configs:/configs
      - .:/app
    working_dir: /app
    ports:
      - "9001:9001"
